### ISSUE TITLE
AttributeError: module 'paste' has no attribute 'intersect'

### ISSUE THREAD

**Issue by mx-ethan-rao** [raphael-group/paste_reproducibility#2]
Hi, when I was trying to run the function load_layer(patient, sample, metadata) under paste_reproducibility/notebooks/scc-analysis-pairwise-and-center.ipynb, it told me "module 'paste' has no attribute 'intersect'". Could you please help take a look on it. I install paste by "pip install paste-bio". Thank you!

**Comment by astrzalk** [comment]
Hi, 

There were very subtle changes made to PASTE as the versions changed. One was that intersect was not explicitly exported in the latest version. 

I will update the README to reflect that the latest version of PASTE might be incompatible with some of these notebooks.  Specifically, all the notebooks should work using paste-bio==1.1.4.

A very easy workaround that I will leave as a comment in the scc analysis notebook when I update is that you can explicitly import intersect from the paste package: `from paste.helper import intersect`

Let me know if that fixes your issue and if you have any other problems.

**Comment by mx-ethan-rao** [comment]
Got you! Thank you,
